services:
  app:
    build: .
    ports:
      - 12369:12369
    restart: always
    volumes:
      - .:/app

  gradio:
    build: .
    ports:
      - 7860:7860
    restart: always
    volumes:
      - .:/app
    command: ["python", "gradio_app.py"]
    depends_on:
      - app
